### ISSUE TITLE
Bindable Button and Quick Control for Swap Displays

### ISSUE THREAD

**Issue by jakedowns** [jakedowns/citra#9]
this would be quick to implement and a majorly nice feature to have

**Comment by jakedowns** [comment]
https://github.com/citra-emu/citra/issues/5885

new branch:
https://github.com/jakedowns/citra/tree/jakedowns/bindableSwapScreenButton

**Comment by boonotakota** [comment]
Hey, I'm sorry to bother! This might be an obnoxious question, but do you have an estimate on the swap screen thing? I just got my lume pad 2 and the default display feels like such a waste of screen space. Thanks!

**Comment by jakedowns** [comment]
> Hey, I'm sorry to bother! This might be an obnoxious question, but do you have an estimate on the swap screen thing? I just got my lume pad 2 and the default display feels like such a waste of screen space. Thanks!

hey there, i'm currently going through the process of getting Citra updated for Lume Pad 2, to the latest citra version + Leia SDK

once i get that published, i plan to dive back into this PR 

unless someone else beats me to it: https://github.com/citra-emu/citra/issues/5885

**Comment by jakedowns** [comment]
merged :D @boonotakota 
new release coming soon

**Comment by jakedowns** [comment]
released https://github.com/jakedowns/citra/releases/tag/v2024_01_25
